#!/usr/bin/env python3
"""
Resynthesize "You've got mail" from measured tracks.

The synthesis half of analysis-by-synthesis. analyze_ref.py measured where the
formants, pitch and loudness went in a reference recording; this drives the
same cascade synthesizer make_voice.py uses with those numbers instead of
hand-guessed ones.

No audio from the reference reaches the output. The input is ref_tracks.json —
a few hundred floats describing articulation, not a waveform. What comes out is
generated by the resonators here, the way a MIDI transcription of a song is not
a copy of the recording.

    python3 make_match.py [outdir]
"""

import json
import os
import sys
from pathlib import Path

import numpy as np

from make_sounds import SR, PEAK, bandpass, finish, write, phone_speaker
from make_voice import glottal, resonator, vocal_rolloff

# Beside this file, not beside the caller. build_sounds.py is invoked from the repo
# root by CI, and a bare relative name silently resolved to nothing there.
TR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ref_tracks.json")
# Path to the reference, used ONLY to fit one static tilt curve (see
# tilt_curve). Set to None to synthesize with no reference present at all.
REF_AUDIO = os.environ.get("MAILBOX_REF") or None


def load():
    d = json.load(open(TR))
    hop, nfr = d["hop"], d["n"]
    # Frame i is centred at i*hop + WIN/2; WIN was 25 ms.
    t = np.arange(nfr) * hop + 0.0125
    n = int(SR * (t[-1] + 0.0125))
    grid = np.arange(n) / SR

    def up(v):
        return np.interp(grid, t, np.asarray(v, dtype=float))

    F = np.array(d["F"])
    B = np.array(d["B"])
    return dict(
        n=n,
        f0=up(d["f0"]),
        amp=up(d["amp"]),
        voiced=up([1.0 if v else 0.0 for v in d["voiced"]]),
        F=[up(F[:, k]) for k in range(4)],
        B=[up(np.clip(B[:, k], 50, 450)) for k in range(4)],
        frames=(t, np.asarray(d["amp"], dtype=float)),
    )


def smooth(x, ms=12):
    k = max(1, int(SR * ms / 1000))
    return np.convolve(x, np.ones(k) / k, "same")


def match_envelope(y, t, target, floor=1e-4):
    """Force the output's loudness contour onto the measured one.

    This matters more than it sounds. A cascade resonator's gain swings by
    tens of dB as F1 moves — the same source through an /ɑ/ and through an /u/
    comes out at wildly different levels — so without this correction the
    synthesized word stresses land in the wrong places even when every formant
    is right. Measure what came out, divide it away, multiply the target in.
    """
    win = int(SR * 0.025)
    got = np.zeros(len(t))
    for i, ti in enumerate(t):
        a = max(0, int(ti * SR) - win // 2)
        b = min(len(y), int(ti * SR) + win // 2)
        got[i] = np.sqrt((y[a:b] ** 2).mean()) if b > a else 0.0
    g = np.where(got > floor, target / np.maximum(got, floor), 0.0)
    g = np.clip(g, 0, np.percentile(g[g > 0], 97) if (g > 0).any() else 1.0)
    gt = np.interp(np.arange(len(y)) / SR, t, g)
    return y * smooth(gt, 15)


def tilt_curve(ref_path, y, amp_track, nfft=4096, quef=28):
    """A static EQ that puts the synthesis on the reference's spectral slope.

    Measured: the resynthesis was systematically dark. The first mel-cepstral
    coefficient — which IS spectral tilt — sat at 12.2 against the reference's
    6.5, and that single offset accounted for 63% of all the distortion. Every
    formant was in the right place and it still would not have sounded right,
    because a glottal source model and a 1989 broadcast chain do not have the
    same slope.

    This is one smooth curve for the whole utterance, fitted to the average
    difference in log spectra. It carries no timing and no articulation — the
    tilt of a microphone, not the sound of a voice.
    """
    from analyze_ref import decode
    ref = decode(ref_path, SR)

    def avg_log_spec(x):
        w, h = int(SR * 0.025), int(SR * 0.005)
        acc = np.zeros(nfft // 2 + 1)
        cnt = 0
        for i in range(min(len(amp_track), (len(x) - w) // h + 1)):
            if amp_track[i] < 0.10:
                continue
            s = x[i * h: i * h + w] * np.hamming(w)
            acc += np.log(np.abs(np.fft.rfft(s, nfft)) + 1e-9)
            cnt += 1
        return acc / max(cnt, 1)

    d = avg_log_spec(ref) - avg_log_spec(y)
    # Keep only the slow part of the difference: a smooth tilt, not the
    # reference's individual harmonics.
    c = np.fft.irfft(d)
    c[quef:-quef] = 0
    d = np.real(np.fft.rfft(c))
    return np.exp(np.clip(d, -2.0, 2.0))


def apply_curve(y, curve):
    """Apply a gain curve across the whole signal.

    The curve is defined on a 4096-point FFT grid and y is ~50k samples, so the
    CURVE gets resampled onto y's frequency grid — not the other way round.
    Calling rfft(y, 4096) instead silently truncates a one-second utterance to
    85 ms, which is what happened the first time.
    """
    n = len(y)
    S = np.fft.rfft(y)
    g = np.interp(np.linspace(0, 1, len(S)), np.linspace(0, 1, len(curve)), curve)
    return np.fft.irfft(S * g, n)


def synth(breathiness=0.010, jitter=0.004, seed=5):
    d = load()
    n = d["n"]
    rng = np.random.default_rng(seed)

    f0 = d["f0"].copy()
    walk = np.cumsum(rng.standard_normal(n))
    f0 *= 1 + jitter * walk / (np.abs(walk).max() or 1) * 5

    v = np.clip(smooth(d["voiced"], 18), 0, 1)
    a = smooth(d["amp"], 8)

    src = glottal(f0) * a * v
    # Frication where the tracker said "energy but not periodic" — the /v/ of
    # "You've" and the release into "mail" live entirely here.
    fric = bandpass(rng.standard_normal(n), 2600, 0.8) * a * (1 - v) * 0.9
    asp = bandpass(rng.standard_normal(n), 2000, 0.7) * a * breathiness

    y = src + fric + asp
    for k in range(4):
        y = resonator(y, d["F"][k], d["B"][k])
    y = resonator(y, np.full(n, 4600.0), np.full(n, 400.0))   # fixed F5

    y = vocal_rolloff(np.diff(y, prepend=0.0))
    y = match_envelope(y, *d["frames"])

    # Put it on the reference's spectral slope, then re-match the envelope
    # (an EQ changes loudness) — order matters, tilt first, level second.
    #
    # The curve is fitted ONCE, with the reference present, and cached into
    # ref_tracks.json. After that the build needs no reference audio at all:
    # everything the synthesizer reads is numbers in a JSON file.
    curve = cached_curve()
    if curve is None and REF_AUDIO:
        curve = tilt_curve(REF_AUDIO, y, d["frames"][1])
        cache_curve(curve)
    if curve is not None:
        y = apply_curve(y, curve)
        y = match_envelope(y, *d["frames"])
    return y


def cached_curve():
    d = json.load(open(TR))
    c = d.get("tilt")
    return np.array(c) if c else None


def cache_curve(curve):
    d = json.load(open(TR))
    d["tilt"] = [round(float(v), 5) for v in curve]
    json.dump(d, open(TR, "w"))


# ─────────────────────────────────────────────────────────────── variants ──

def match():
    """The straight resynthesis."""
    return synth()


def match_chip():
    """Same articulation, run through an 8 kHz 6-bit speech chip."""
    y = synth(breathiness=0.014, jitter=0.007, seed=13)
    hold = 6
    y = np.repeat(y[::hold], hold)[: len(y)]
    y = np.round(y / (np.abs(y).max() or 1) * 40) / 40
    return bandpass(y, 1500, 0.55)


def match_lofi():
    """4 kHz, 4-bit, aliasing left in. A talking toy that knows the line."""
    y = synth(breathiness=0.018, jitter=0.011, seed=17)
    hold = 12
    y = np.repeat(y[::hold], hold)[: len(y)]
    y = np.round(y / (np.abs(y).max() or 1) * 7) / 7
    return bandpass(y, 1300, 0.5)


MATCHES = {
    "match":      (match,      "You've Got Mail — Synth",
                   "Resynthesized from measured formant, pitch and level tracks."),
    "match_chip": (match_chip, "You've Got Mail — Synth Chip",
                   "The same articulation through an 8 kHz 6-bit chip."),
    "match_lofi": (match_lofi, "You've Got Mail — Synth Lo-Fi",
                   "4 kHz, 4-bit, aliasing intact."),
}


def main():
    if not Path(TR).exists():
        sys.exit(f"missing {TR} — run analyze_ref.py first")
    out = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    (out / "phone-sim").mkdir(parents=True, exist_ok=True)
    for key, (fn, name, note) in MATCHES.items():
        x = finish(fn())
        dur = write(out / f"{key}.wav", x)
        write(out / "phone-sim" / f"{key}.wav", phone_speaker(x))
        print(f"{key:11s} {dur*1000:6.0f} ms   {name}")


if __name__ == "__main__":
    main()
